title: "ECE M202A"
remote_theme: pmarsceill/just-the-docs

# Color scheme supports "light" (default) and "dark"
color_scheme: light

search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "On GitHub":
    - "//github.com/ucla-ecem202a/ucla-ecem202a.github.io"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

